---
- name: "Install the correct repository"
  include: "RedHat.yml"
  when: ansible_os_family == "RedHat"

- name: "Install the correct repository"
  include: "Suse.yml"
  when: ansible_os_family == "Suse"
