---
- name: Add yum common repositories
  template: src=yum.repo.j2 dest="/etc/yum.repos.d/{{ item.name }}.repo" owner=root group=root mode=0644
  with_items: "{{ yum_common_repos }}"
  when: yum_common_repos is defined

- name: Add yum repositories
  template: src=yum.repo.j2 dest=/etc/yum.repos.d/{{item.name}}.repo owner=root group=root mode=0644
  with_items: "{{ yum_repos }}"
  when: yum_repos is defined

- include: epel.yml
  whenl: repo_epel == True

- name: Yum makecache
  shell: yum makecache
  changed_when: False
  ignore_errors: yes
